spring:
  application:
    name: eureka-server-ha
server:
  port: 8001
eureka:
  instance:
    hostname: eureka-server-1.com
    instance-id: eureka-server-1
  client:
    serviceUrl:
      defaultZone: http://eureka-server-2.com:8002/eureka/,http://eureka-server-3.com:8003/eureka/