package com.example.demo.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_id
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.fb_id
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String fbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.num
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.account
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.real_name
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.phone
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mobile
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sex
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.birth_y
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private Integer birthY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.birth_m
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private Integer birthM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.birth_d
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private Integer birthD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.area_1
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String area1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.area_2
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String area2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ecode
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String ecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.address
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.zhi_ye
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String zhiYe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.erp_flag
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private Integer erpFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.open_flag
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private Integer openFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.score
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.onlystr
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String onlystr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.udate
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    private String udate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_id
     *
     * @return the value of member.member_id
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_id
     *
     * @param memberId the value for member.member_id
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.fb_id
     *
     * @return the value of member.fb_id
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getFbId() {
        return fbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.fb_id
     *
     * @param fbId the value for member.fb_id
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setFbId(String fbId) {
        this.fbId = fbId == null ? null : fbId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.num
     *
     * @return the value of member.num
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.num
     *
     * @param num the value for member.num
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.account
     *
     * @return the value of member.account
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.account
     *
     * @param account the value for member.account
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password
     *
     * @return the value of member.password
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password
     *
     * @param password the value for member.password
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.real_name
     *
     * @return the value of member.real_name
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.real_name
     *
     * @param realName the value for member.real_name
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.phone
     *
     * @return the value of member.phone
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.phone
     *
     * @param phone the value for member.phone
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mobile
     *
     * @return the value of member.mobile
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mobile
     *
     * @param mobile the value for member.mobile
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email
     *
     * @return the value of member.email
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email
     *
     * @param email the value for member.email
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sex
     *
     * @return the value of member.sex
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sex
     *
     * @param sex the value for member.sex
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birth_y
     *
     * @return the value of member.birth_y
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public Integer getBirthY() {
        return birthY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birth_y
     *
     * @param birthY the value for member.birth_y
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setBirthY(Integer birthY) {
        this.birthY = birthY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birth_m
     *
     * @return the value of member.birth_m
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public Integer getBirthM() {
        return birthM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birth_m
     *
     * @param birthM the value for member.birth_m
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setBirthM(Integer birthM) {
        this.birthM = birthM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birth_d
     *
     * @return the value of member.birth_d
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public Integer getBirthD() {
        return birthD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birth_d
     *
     * @param birthD the value for member.birth_d
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setBirthD(Integer birthD) {
        this.birthD = birthD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.area_1
     *
     * @return the value of member.area_1
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getArea1() {
        return area1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.area_1
     *
     * @param area1 the value for member.area_1
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setArea1(String area1) {
        this.area1 = area1 == null ? null : area1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.area_2
     *
     * @return the value of member.area_2
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getArea2() {
        return area2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.area_2
     *
     * @param area2 the value for member.area_2
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setArea2(String area2) {
        this.area2 = area2 == null ? null : area2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ecode
     *
     * @return the value of member.ecode
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getEcode() {
        return ecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ecode
     *
     * @param ecode the value for member.ecode
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setEcode(String ecode) {
        this.ecode = ecode == null ? null : ecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.address
     *
     * @return the value of member.address
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.address
     *
     * @param address the value for member.address
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.zhi_ye
     *
     * @return the value of member.zhi_ye
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getZhiYe() {
        return zhiYe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.zhi_ye
     *
     * @param zhiYe the value for member.zhi_ye
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setZhiYe(String zhiYe) {
        this.zhiYe = zhiYe == null ? null : zhiYe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.erp_flag
     *
     * @return the value of member.erp_flag
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public Integer getErpFlag() {
        return erpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.erp_flag
     *
     * @param erpFlag the value for member.erp_flag
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setErpFlag(Integer erpFlag) {
        this.erpFlag = erpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.open_flag
     *
     * @return the value of member.open_flag
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public Integer getOpenFlag() {
        return openFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.open_flag
     *
     * @param openFlag the value for member.open_flag
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setOpenFlag(Integer openFlag) {
        this.openFlag = openFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.score
     *
     * @return the value of member.score
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.score
     *
     * @param score the value for member.score
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.onlystr
     *
     * @return the value of member.onlystr
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getOnlystr() {
        return onlystr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.onlystr
     *
     * @param onlystr the value for member.onlystr
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setOnlystr(String onlystr) {
        this.onlystr = onlystr == null ? null : onlystr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.udate
     *
     * @return the value of member.udate
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public String getUdate() {
        return udate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.udate
     *
     * @param udate the value for member.udate
     *
     * @mbg.generated Thu Sep 12 21:00:38 CST 2019
     */
    public void setUdate(String udate) {
        this.udate = udate == null ? null : udate.trim();
    }
}